### PR TITLE
Dynamically themed Strata Logo

### PR DESCRIPTION
**Pull request by ZenithRogue**
Automatically choose between dark and light theme logo

See discussion https://github.com/StrataSource/strata-branding/pull/7

### CODE REVIEW

**Comment by ZenithRogue** [comment]
@LauraWebdev Looping you in on this side

**Review by LauraWebdev — APPROVED** [review]
I'd be down for this variant for our docs.

**Comment by ZenithRogue** [comment]
this isnt a new variant, this is both existing variants of the logo controlled by a source media tag
```html
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://branding.stratasource.org/i/strata/logo/ondark/color.svg">
    <img width=512 src="https://branding.stratasource.org/i/strata/logo/onlight/color.svg">
  </picture>
```

**Comment by ZenithRogue** [comment]
@LauraWebdev just checking in on this PR, anything else need to be done before you guys merge?

**Review by JJL772 — APPROVED** [review]
Sorry for the late approval, forgot to check on this!

Thanks for your work on this!

**Pull request merged**
